title = 'Website'
languageCode = 'en-us'
baseURL = 'https://iHaras.org'
copyright = 'İbrahim Haras'
disableHugoGeneratorInject = true
# Comment
# Comment 2
# Comment 3
# Comment 4
# Comment 5
# Commont 6
# Comment X
